# Generated by Django 3.2.16 on 2023-10-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20231001_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='author',
        ),
    ]
